name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: "3.10"}
    - run: pip install poetry
    - run: poetry install
    - run: poetry run ruff check .
    - run: poetry run mypy src
    - run: poetry run pytest --cov=src --cov-fail-under=85
