capital_usd: 10000
universe:
  symbols: ["BTC/USDT","ETH/USDT","SOL/USDT","ADA/USDT","DOGE/USDT"]
risk:
  max_drawdown_pct: 18
  adv_cap_pct: 2
  stop_loss_pct: 8
  var_confidence: 0.95
  turnover_cap_pct: 25
  cluster_cap: 0.2
  min_adv_usd: 50000
  min_mcap_usd: 5000000
  corr_spike_thresh: 0.6
model:
  zscore_threshold: 2.5
  volume_sigma: 3.0
  sentiment_min_polarity: 0.15
  min_confidence: 0.75
  arima_order: [2,0,2]
  consensus_thr: 0.6
meta:
  sharpe_floor: 1.2
  hitrate_floor: 0.6
